portafolio2/atividades en clase/api/urls.py
from django.urls import path
from api import views



app_name = "api"


urlpatterns = [
    
]

portafolio2/atividades en clase/core/urls.py
from django.urls import path
from core import views



app_name = "core"


urlpatterns = [
    path('list/grantgoal/', views.ListGrantGoal.as_view(), name="gg_list"),
    path('create/grantgoal/', views.CreateGrantGoal.as_view(), name="gg_create"),
    path('detail/grantgoal/<int:pk>/', views.DetailGrantGoal.as_view(), name="gg_detail"),
    path('update/grantgoal/<int:pk>/', views.UpdateGrantGoal.as_view(), name="gg_update"),
    path('delete/grantgoal/<int:pk>/', views.DeleteGrantGoal.as_view(), name="gg_delete"),
]

portafolio2/atividades en clase/cplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("api.urls")),
    path('core/', include("core.urls")),
    path('', include("home.urls")),
]

portafolio2/atividades en clase/home/urls.py
from django.urls import path
from home import views



app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
]

portafolio2/atividades en clase/urls.py
from django.urls import path
from home import views



app_name = "home"


urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about"),    
    path('identity/', views.Identity.as_view(), name="identity"),
    path('contact/', views.Contact.as_view(), name="contact"),
]

portafolio2/atividades en clase/core/models.py
from django.db import models

from django.contrib.auth.models import User

from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

#### GRANT GOAL ####
STATE_CHOICES = (
    ('Done', 'DN'),
    ('Doing', 'DG'),
    ('Not Stared', 'NS'),
)
class GrantGoal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gg_title = models.CharField(max_length=128, default="Generic Grant Goal Title")
    description = models.CharField(max_length=256, default="Generic Grant Goal Description")
    timestamp = models.DateField(auto_now_add=True)
    days_duration = models.IntegerField(default=7)
    final_date = models.DateField(auto_now_add=False, auto_now=False, blank=True, null=True)
    status = models.BooleanField(default=True)
    state = models.CharField(max_length=16, choices=STATE_CHOICES)
    sprint = models.IntegerField(default=1)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.gg_title



# ## SIGNALS 
# ### post_save
@receiver(post_save, sender=GrantGoal)
def end_time_grantgoal(sender, instance, **kwargs):
    if instance.final_date is None or instance.final_date=='':
        instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
        instance.save()


# @receiver(post_save, sender=GrantGoal)
# def end_time_grantgoal(sender, instance, **kwargs):
#     if instance.final_date is None or instance.final_date=='':
#         instance.final_date = instance.timestamp + timedelta(days=instance.days_duration)
#         instance.save()




#### GOALS ####


#### SUBGOALS ####


#### ISSUES ####

portafolio2/atividades en clase/home/models.py
from django.db import models

# Create your models here.

portafolio2/atividades en clase/core/forms.py
from django import forms
from .models import GrantGoal

class GrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = "__all__"
        exclude = ["timestamp", "final_date"]
        widgets = {
            "user": forms.Select(attrs={"type":"select","class":"form-select"}),
            "gg_title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del GrantGoal"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"Escribe la descripcion del GrantGoal"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
            "state": forms.Select(attrs={"type":"select","class":"form-select"}),
            "sprint":forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el codigo del GrantGoal"}),
        }



class UpdateGrantGoalForm(forms.ModelForm):
    class Meta:
        model = GrantGoal
        fields = "__all__"
        exclude = ["timestamp", "final_date"]
        widgets = {
            "user": forms.Select(attrs={"type":"select","class":"form-select"}),
            "gg_title": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el nombre del GrantGoal"}),
            "description": forms.Textarea(attrs={"type":"text", "class":"form-control", "rows":3, "placeholder":"Escribe la descripcion del GrantGoal"}),
            "days_duration": forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "status": forms.CheckboxInput(attrs={"type":"checkbox", "class":"form-checkbox"}),
            "state": forms.Select(attrs={"type":"select","class":"form-select"}),
            "sprint":forms.NumberInput(attrs={"type":"number", "class":"form-control"}),
            "slug":forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe el codigo del GrantGoal"}),
        }

portafolio2/atividades en clase/api/views.py
from django.shortcuts import render

# Create your views here.

portafolio2/atividades en clase/core/views.py
from django.shortcuts import render

from django.views import generic

from django.urls import reverse_lazy
from .models import GrantGoal
from .forms import GrantGoalForm, UpdateGrantGoalForm
# Create your views here.

##### G R A N T G O A L C R U D #####

##Create
class CreateGrantGoal(generic.CreateView):
    template_name = "core/gg_create.html"
    model = GrantGoal
    form_class = GrantGoalForm
    success_url = reverse_lazy("core:gg_list")


## Retrieve
#List GrantGoal
class ListGrantGoal(generic.View):
    template_name = "core/gg_list.html"
    context = {}

    def get(self, request, *args, **kwargs):
        queryset = GrantGoal.objects.filter(status=True)
        self.context = {
            "grant_goals": queryset
        }
        return render(request, self.template_name, self.context)


#Detail
class DetailGrantGoal(generic.DetailView):
    template_name = "core/gg_detail.html"
    model = GrantGoal


#Update
class UpdateGrantGoal(generic.UpdateView):
    template_name = "core/gg_update.html"
    model = GrantGoal
    form_class = UpdateGrantGoalForm
    success_url = reverse_lazy("core:gg_list")


#Delete
class DeleteGrantGoal(generic.DeleteView):
    template_name = "core/gg_delete.html"
    model = GrantGoal
    success_url = reverse_lazy("core:gg_list")

portafolio2/atividades en clase/home/views.py
from django.shortcuts import render
from django.views import generic



# Create your views here.

class Index(generic.View):
    template_name = "home/index.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "molinero",
            "lista": [1, 2, 3]
        }
        return render(request, self.template_name, self.context)
    

class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "molinero"
        }
        return render(request, self.template_name, self.context)


class Identity(generic.View):
    template_name = "molinero"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "molinero"
        }
        return render(request, self.template_name, self.context)


class Contact(generic.View):
    template_name = "home/contact.html"
    context = {}

    def get(self, request, *args, **kwargs):
        self.context = {
            "name": "molinero"
        }
        return render(request, self.template_name, self.context)

portafolio2/atividades en clase/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <nav class="navbar navbar-expand-lg bg-body-tertiary">
                    <div class="container-fluid">
                      <a class="navbar-brand" href="#">Navbar</a>
                      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                      </button>
                      <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                          <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:about' %}">About</a>
                          </li>
                          <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                              Dropdown
                            </a>
                            <ul class="dropdown-menu">
                              <li><a class="dropdown-item" href="#">Action</a></li>
                              <li><a class="dropdown-item" href="#">Another action</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                          </li>
                        </ul>
                        <form class="d-flex" role="search">
                          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                          <button class="btn btn-outline-success" type="submit">Search</button>
                        </form>
                      </div>
                    </div>
                  </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-2">

            </div>
            <div class="col-10">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <!-- Footer -->
                <footer class="text-center text-lg-start bg-light text-muted">
                    <!-- Section: Social media -->
                    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
                    <!-- Left -->
                    <div class="me-5 d-none d-lg-block">
                        <span>Get connected with us on social networks:</span>
                    </div>
                    <!-- Left -->
                
                    <!-- Right -->
                    <div>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-twitter"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-google"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-instagram"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-linkedin"></i>
                        </a>
                        <a href="" class="me-4 text-reset">
                        <i class="fab fa-github"></i>
                        </a>
                    </div>
                    <!-- Right -->
                    </section>
                    <!-- Section: Social media -->
                
                    <!-- Section: Links  -->
                    <section class="">
                    <div class="container text-center text-md-start mt-5">
                        <!-- Grid row -->
                        <div class="row mt-3">
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                            <!-- Content -->
                            <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Company name
                            </h6>
                            <p>
                            Here you can use rows and columns to organize your footer content. Lorem ipsum
                            dolor sit amet, consectetur adipisicing elit.
                            </p>
                        </div>
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                            Products
                            </h6>
                            <p>
                            <a href="#!" class="text-reset">Angular</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">React</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">Vue</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">Laravel</a>
                            </p>
                        </div>
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                            </h6>
                            <p>
                            <a href="#!" class="text-reset">Pricing</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">Settings</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">Orders</a>
                            </p>
                            <p>
                            <a href="#!" class="text-reset">Help</a>
                            </p>
                        </div>
                        <!-- Grid column -->
                
                        <!-- Grid column -->
                        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                            <!-- Links -->
                            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                            <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                            <p>
                            <i class="fas fa-envelope me-3"></i>
                            info@example.com
                            </p>
                            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
                        </div>
                        <!-- Grid column -->
                        </div>
                        <!-- Grid row -->
                    </div>
                    </section>
                    <!-- Section: Links  -->
                
                    <!-- Copyright -->
                    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
                    © 2021 Copyright:
                    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
                    </div>
                    <!-- Copyright -->
                </footer>
                <!-- Footer -->   
            </div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

portafolio2/atividades en clase/templates/core/gg_create.html
{% extends "base/base.html" %}

{% block title %}
  CREATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Create GrantGoal</button>
        <a href="{% url 'core:gg_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

portafolio2/atividades en clase/templates/core/gg_delete.html
{% extends "base/base.html" %}

{% block title %}
  DELETE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas Eliminar al GrantGoal: {{ object }}?
        <button type="submit" class="btn btn-outline-danger">Delete GrantGoal</button>
        <a href="{% url 'core:gg_list'%}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

portafolio2/atividades en clase/templates/core/gg_detail.html
{% extends "base/base.html" %}

{% block title %}
  DETAIL GRANTGOAL VIEW
{% endblock title %}


{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ object.gg_title }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the grantgoal: {{ object.gg_title }} .</strong> <br>
          Grantgoal Description: {{ object.description }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Date Data
        </button>
      </h2>
      <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the timestamp {{ object.timestamp }} to grantgoal {{ object.gg_title }} </strong> with Duration {{ object.days_duration }} days, The Deadline grantgoal is: {{ object.final_date }}
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingThree">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Status Grant Goal
        </button>
      </h2>
      <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          <strong>This is the status {{ object.status }} for the {{ object.gg_title }} </strong> Its state is: {{ object.state }}
        </div>
      </div>
    </div>
  </div>
  
  <a href="{% url 'core:gg_list' %}">back to list</a>
{% endblock content %}

portafolio2/atividades en clase/templates/core/gg_list.html
{% extends 'base/base.html' %}

{% block title %} LIST GRANT GOAL VIEW {% endblock title %}

{% block content %}


    <a href="{% url 'core:gg_create' %}" class="btn btn-outline-success form-control">Create a New GrantGoal</a>
    <table class="table table-striped table-hover">
        <thead>
            <th>ID</th>
            <th>GG TITLE</th>
            <th>TIMESTAMP</th>
            <th>DAYS DURATION</th>
            <th>USER</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for gg in grant_goals %}
                <tr>
                    <td>{{ gg.id }}</td>
                    <td>{{ gg.gg_title }}</td>
                    <td>{{ gg.timestamp }}</td>
                    <td>{{ gg.days_duration }}</td>
                    <td>{{ gg.user }}</td>
                    <td><a href="{% url 'core:gg_detail' gg.id %}" class="btn btn-outline-info"> Detail </a></td>
                    <td><a href="{% url 'core:gg_update' gg.id %}" class="btn btn-outline-warning"> Update</a></td>
                    <td><a href="{% url 'core:gg_delete' gg.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
   
{% endblock content %}

portafolio2/atividades en clase/templates/core/gg_update.html
{% extends "base/base.html" %}

{% block title %}
  UPDATE GRANT GOAL VIEW
{% endblock title %}

{% block content %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-primary">Update GrantGoal</button>
        <a href="{% url 'core:gg_list' %}" class="btn btn-outline-warning">Cancel</a>
    </form>
{% endblock content %}

portafolio2/atividades en clase/templates/home/about.html
{% extends "base/base.html" %}




{% block title %} About View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a About XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

portafolio2/atividades en clase/templates/home/contact.html
{% extends "base/base.html" %}




{% block title %} Contact View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a Contact XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

portafolio2/atividades en clase/templates/home/identity.html
{% extends "base/base.html" %}




{% block title %} Identity View {% endblock title %}

{% block content %}
    <h1>Hola {{ name }} Bienvido a Identity XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
{% endblock content %}

portafolio2/atividades en clase/templates/home/index.html
{% extends "base/base.html" %}




{% block title %} Index View {% endblock title %}

{% block content %}
    
    <h1>Hola {{ name }} Bienvido a Django XD</h1>
    <button class="btn btn-outline-danger">Test Bootstrap</button>
    <br>
    <br><br>
    <br><br>
    <br>
    <br>
    <table class="table">
        {% for i in name %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ name }}</td>
            <td>1289</td>
        </tr>  
        {% endfor %}
    </table>
    
    
{% endblock content %}